### ISSUE TITLE
please confirm: "Change the indexing options of a hdb of bdb-Database."

### ISSUE THREAD

**Issue by marguerite** [yast/yast-ldap-server#11]
in src/include/ldap-server/helps.rb:137:

Change the indexing options of a hdb of bdb-Database.

Is the "of" in this term right?

Isn't that "or"?

From a translator's view, I thought hdb/bdb are two different terms. 

How can they include each other?

Marguerite

**Comment by dgdavid** [comment]
Hi @marguerite !

Please, accept our apologies for overlooking your issue report for a really quite long time.

As you can see in the README of this repo, 

> The development of this module was stopped

five years ago. So, as part of the issues clean-up that we're doing this week, I'm going to close the  issue.

Thank you for your understanding.

**Comment by dgdavid** [comment]
Anyway, the mentioned help text was already removed at https://github.com/yast/yast-auth-server/commit/d8967d76813cb10337777a9c2968d406942d44c8#diff-3a8f419588599a43ebf937ade846d148L145
